// Auto-generated by cli/scripts/generate-version.sh — do not edit by hand.
// The committed stub uses "0.0.0-dev" placeholders so plain swift build
// works for devs; release-build.sh regenerates this file from git state
// (then reverts it post-build) so released binaries report the real tag.
enum BuildInfo {
    static let marketing = "1.0.0"
    static let gitDescribe = "v1.0.0-dirty"
    static let buildTimestamp = "2026-04-28T04:10:28Z"
    static let full = "1.0.0 (v1.0.0-dirty, built 2026-04-28T04:10:28Z)"
}
