#!/usr/bin/env bash
#
# Regenerate cli/Sources/testanyware/Version.swift from git state, mirroring
# Ravel-Lite's build.rs strategy (CARGO_PKG_VERSION + git describe + UTC
# timestamp). Invoked by scripts/release-build.sh just before each release
# build of the CLI; release-build.sh reverts the file after the build so the
# working tree stays clean.
#
# Devs can also run this manually to make their dev binary's --version
# reflect the current commit. The checked-in stub uses "0.0.0-dev" so plain
# `swift build` works without ever invoking this script.

set -euo pipefail
IFS=$'\n\t'

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$script_dir/../Sources/testanyware/Version.swift"

cd "$script_dir/.."

git_describe="$(git describe --tags --always --dirty 2>/dev/null || echo unknown)"
timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
marketing="$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0-dev")"

cat > "$out" <<EOF
// Auto-generated by cli/scripts/generate-version.sh — do not edit by hand.
// The committed stub uses "0.0.0-dev" placeholders so plain swift build
// works for devs; release-build.sh regenerates this file from git state
// (then reverts it post-build) so released binaries report the real tag.
enum BuildInfo {
    static let marketing = "$marketing"
    static let gitDescribe = "$git_describe"
    static let buildTimestamp = "$timestamp"
    static let full = "$marketing ($git_describe, built $timestamp)"
}
EOF
