#!/usr/bin/env bash
#
# Regenerate cli/Sources/testanyware/LLMInstructions.generated.swift from
# cli/LLM_INSTRUCTIONS.md. The guide is embedded as a base64 blob so it is
# compiled into the binary and ships intact with a Homebrew install (no
# repo, no resource bundle required).
#
# Mirrors generate-version.sh: invoked by scripts/release-build.sh before
# each release build, and runnable by hand after editing the guide. The
# checked-in generated file lets a plain `swift build` work without it.

set -euo pipefail
IFS=$'\n\t'

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
md="$script_dir/../LLM_INSTRUCTIONS.md"
out="$script_dir/../Sources/testanyware/LLMInstructions.generated.swift"

[[ -f "$md" ]] || { echo "generate-llm-instructions: missing $md" >&2; exit 1; }

b64="$(base64 < "$md" | tr -d '\n')"

cat > "$out" <<EOF
// Auto-generated by cli/scripts/generate-llm-instructions.sh — do not edit by hand.
// Source: cli/LLM_INSTRUCTIONS.md. The guide is embedded as base64 so it is
// compiled into the binary and ships with a Homebrew install.
import Foundation

enum LLMInstructions {
    private static let base64 = "$b64"

    /// The full LLM usage guide as plain text.
    static var text: String {
        guard let data = Data(base64Encoded: base64) else { return "" }
        return String(decoding: data, as: UTF8.self)
    }
}
EOF

echo "generate-llm-instructions: wrote $out" >&2
